styles:
  content:
    defaultHeaderType: 3
    image:
      lazyLoading: lazy
    textmedia:
      maxW: 1600
      maxWInText: 640
      columnSpacing: 15
      rowSpacing: 15
      borderColor: '#000000'
      borderWidth: 2
      borderPadding: 0